"""Build the repository-root Docket GitHub evidence kit served by the frontend."""

from pathlib import Path
from zipfile import ZIP_DEFLATED, ZipFile, ZipInfo


ROOT = Path(__file__).resolve().parents[1]
ACTION = ROOT / "integrations" / "github-action"
OUTPUT = ROOT / "frontend" / "public" / "docket-github-kit.zip"

FILES = {
    ACTION / "action.yml": ".docket/github-action/action.yml",
    ACTION / "src" / "index.js": ".docket/github-action/src/index.js",
    ACTION / "README.md": ".docket/github-action/README.md",
    ACTION / "target-repo-workflow.yml": ".github/workflows/docket-evidence.yml",
}

SETUP = """# Install the Docket GitHub evidence kit

1. Extract this archive at the root of the public task repository.
2. Add the exact docket.yml generated by the Docket app at the repository root.
3. Commit .docket/, .github/workflows/docket-evidence.yml, and docket.yml.
4. Open or update the delivery pull request.
5. Wait for the Docket evidence workflow to complete successfully.
6. Open the shared Docket case and select Find matching delivery.

The workflow uses a read-only contents token, persists no checkout credentials,
and produces public evidence only. Never put secrets or private URLs in docket.yml.
"""


def add_bytes(archive: ZipFile, name: str, payload: bytes) -> None:
    info = ZipInfo(name, date_time=(1980, 1, 1, 0, 0, 0))
    info.compress_type = ZIP_DEFLATED
    info.external_attr = 0o100644 << 16
    archive.writestr(info, payload)


def main() -> None:
    missing = [str(path) for path in FILES if not path.is_file()]
    if missing:
        raise SystemExit(f"Missing GitHub kit source files: {', '.join(missing)}")
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with ZipFile(OUTPUT, "w") as archive:
        for source, destination in sorted(FILES.items(), key=lambda item: item[1]):
            add_bytes(archive, destination, source.read_bytes())
        add_bytes(archive, "DOCKET_SETUP.md", SETUP.encode("utf-8"))
    print(OUTPUT)


if __name__ == "__main__":
    main()
